services:
  - type: web
    name: number-plate-masker-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      mkdir -p static/uploads static/output
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1
    healthCheckPath: /health

  - type: web
    name: number-plate-masker-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://carnumberplatemasker.onrender.com
    staticPublishPath: frontend/dist 