services:
  - type: web
    name: carnumberplatemasker
    env: python
    buildCommand: |
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
      
      # Install backend dependencies
      cd backend
      pip install -r requirements.txt
      mkdir -p static/uploads static/output
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1
    healthCheckPath: /health

  - type: static
    name: carnumberplatemasker-frontend
    env: node
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    envVars:
      - key: VITE_API_URL
        value: https://carnumberplatemasker.onrender.com
    staticPublishPath: dist 