services:
  - type: web
    name: carnumberplatemasker
    env: python
    buildCommand: |
      # Create and activate virtual environment
      python -m venv .venv
      source .venv/bin/activate
      
      # Install backend dependencies first
      pip install -r backend/requirements.txt
      mkdir -p backend/static/uploads backend/static/output
      
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: |
      source .venv/bin/activate
      cd backend
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1
    healthCheckPath: /health

  - type: static
    name: carnumberplatemasker-frontend
    env: node
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    envVars:
      - key: VITE_API_URL
        value: https://carnumberplatemasker.onrender.com
    staticPublishPath: dist 